services:
  postgres:
    image: postgres:15
    container_name: calc-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    restart: unless-stopped
    command: start-dev
    environment:
      TZ: America/Los_Angeles
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - '8080:8080'
    depends_on:
      postgres:
        condition: service_healthy
  
  redis:
    image: redis:7-alpine
    container_name: calc-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
  
  backend:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: calc-backend
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      postgres:
        condition: service_healthy
      keycloak:
        condition: service_started
      redis:
        condition: service_started

volumes:
  pgdata: